# Generated by Django 3.1.1 on 2020-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='UNKNOWN', max_length=80)),
                ('last_name', models.CharField(default='UNKNOWN', max_length=80)),
                ('nickname', models.CharField(default='UNKNOWN', max_length=80)),
                ('birth_date', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(default='UNKNOWN', max_length=80)),
                ('character_code', models.CharField(default='UNKUNK', max_length=6)),
                ('nationality', models.CharField(default='--', max_length=2)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('skin_color', models.CharField(max_length=80)),
                ('hair_color', models.CharField(max_length=80)),
                ('iris_color', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
        ),
    ]
