# Generated by Django 3.1.1 on 2020-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='UNKNOWN', max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, default='UNKNOWN', max_length=80, null=True)),
                ('nickname', models.CharField(blank=True, default='UNKNOWN', max_length=80, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='UNKNOWN', max_length=80, null=True)),
                ('character_code', models.CharField(blank=True, default='UNKUNK', max_length=6, null=True)),
                ('nationality', models.CharField(blank=True, default='--', max_length=2, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=80, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=80, null=True)),
                ('iris_color', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
