# Generated by Django 3.1.1 on 2020-09-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_code',
            field=models.CharField(blank=True, default='UNKUNK', max_length=6),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='iris_color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='nationality',
            field=models.CharField(blank=True, default='--', max_length=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='nickname',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin_color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
