# Generated by Django 3.1.1 on 2020-09-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_code',
        ),
        migrations.RemoveField(
            model_name='character',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='height',
        ),
        migrations.RemoveField(
            model_name='character',
            name='iris_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='character',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skin_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weight',
        ),
        migrations.AddField(
            model_name='character',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
