# Generated by Django 3.1.1 on 2020-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneBuilder',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_code',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='root_line',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='scene_number',
        ),
        migrations.AddField(
            model_name='scene',
            name='code',
            field=models.CharField(default='', max_length=12),
        ),
    ]
