# Generated by Django 3.1.1 on 2020-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_scenebuilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='character_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='root_line',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenebuilder',
            name='scene_code',
            field=models.TextField(default=''),
        ),
    ]
