# Generated by Django 3.1.2 on 2020-10-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0004_auto_20200920_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='code',
        ),
    ]
