# Generated by Django 3.1.1 on 2020-09-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0004_line_character'),
        ('scenes', '0004_auto_20200920_2058'),
        ('responses', '0002_auto_20200920_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='next_line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_line', to='lines.line'),
        ),
        migrations.AddField(
            model_name='response',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenes.scene'),
        ),
    ]
