# Generated by Django 3.1.2 on 2020-10-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0007_auto_20201005_1256'),
        ('responses', '0003_auto_20200920_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='response',
            name='code',
        ),
        migrations.RemoveField(
            model_name='response',
            name='scene',
        ),
        migrations.AlterField(
            model_name='response',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lines.line'),
        ),
        migrations.AlterField(
            model_name='response',
            name='next_line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_line', to='lines.line'),
        ),
    ]
