# Generated by Django 3.1.2 on 2020-10-13 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lines', '0009_auto_20201013_2209'),
        ('responses', '0005_response_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lines.line'),
        ),
        migrations.AlterField(
            model_name='response',
            name='next_line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_line', to='lines.line'),
        ),
    ]
