# Generated by Django 3.1.1 on 2020-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_code', models.CharField(max_length=6)),
                ('line_code', models.IntegerField(default=0)),
                ('line_text', models.CharField(max_length=200)),
            ],
        ),
    ]
