# Generated by Django 3.1.1 on 2020-09-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_auto_20200920_1932'),
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='line',
            name='scene',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scenes.scene'),
        ),
        migrations.AlterField(
            model_name='line',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
