# Generated by Django 3.1.1 on 2020-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='inter_id',
            field=models.IntegerField(default=0),
        ),
    ]
