# Generated by Django 3.1.1 on 2020-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_line_inter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='character_code',
        ),
        migrations.RemoveField(
            model_name='line',
            name='inter_id',
        ),
        migrations.AlterField(
            model_name='line',
            name='line_code',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_text',
            field=models.TextField(),
        ),
    ]
