# Generated by Django 3.1.1 on 2020-09-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_auto_20200917_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='line_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_code',
        ),
        migrations.AddField(
            model_name='line',
            name='code',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
