# Generated by Django 3.1.2 on 2020-10-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0004_auto_20200920_2058'),
        ('characters', '0002_auto_20200920_1606'),
        ('lines', '0005_line_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.character'),
        ),
        migrations.AlterField(
            model_name='line',
            name='scene',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='scenes.scene'),
        ),
    ]
