# Generated by Django 3.1.2 on 2020-10-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0006_auto_20201005_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='line',
            name='code',
        ),
    ]
