# Generated by Django 3.1.2 on 2020-10-13 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200920_1606'),
        ('lines', '0007_auto_20201005_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
    ]
