# Generated by Django 3.1.2 on 2020-10-13 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0005_remove_scene_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lines', '0008_auto_20201013_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='line',
            name='scene',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenes.scene'),
        ),
    ]
