# Generated by Django 3.1.1 on 2020-09-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_scene_characters'),
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thought',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='thought',
            name='code',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='thought',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenes.scene'),
        ),
    ]
