# Generated by Django 3.1.1 on 2020-09-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200920_1606'),
        ('thoughts', '0002_auto_20200920_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
    ]
